/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Employee;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cartman
 */
public class FrmMain extends javax.swing.JFrame {

    private Employee employee;

    /**
     * Creates new form FrmMain
     */
    public FrmMain(Employee employee) {
        this.employee = employee;
        initComponents();
        setTitle(employee.getName() + " " + employee.getSurname());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarMain = new javax.swing.JMenuBar();
        menuClient = new javax.swing.JMenu();
        menuTreatment = new javax.swing.JMenu();
        menuAppointment = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuClient.setText("Client");
        menuClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientMouseClicked(evt);
            }
        });
        menuClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientActionPerformed(evt);
            }
        });
        menuBarMain.add(menuClient);

        menuTreatment.setText(" Treatment");
        menuBarMain.add(menuTreatment);

        menuAppointment.setText(" Appointment");
        menuBarMain.add(menuAppointment);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientActionPerformed

    }//GEN-LAST:event_menuClientActionPerformed

    private void menuClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientMouseClicked
        try {
            new FrmClient().setVisible(true);

//            JDialog dialog = new JDialog(this, "New Person", true);
//            JPanel panel = new FrmClient();
//            dialog.add(new FrmClient());
//            dialog.add(panel);
//            dialog.pack();
//            dialog.setLocationRelativeTo(this);
//            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//            dialog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can not initialize view!\n" + ex.getMessage(), "New Person", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuClientMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAppointment;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuClient;
    private javax.swing.JMenu menuTreatment;
    // End of variables declaration//GEN-END:variables
}
